// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetRecapParams is parameters of getRecap operation.
type GetRecapParams struct {
	// Идентификатор recap.
	ID UUID
}

func unpackGetRecapParams(packed middleware.Parameters) (params GetRecapParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(UUID)
	}
	return params
}

func decodeGetRecapParams(args [1]string, argsEscaped bool, r *http.Request) (params GetRecapParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ID = UUID(paramsDotIDVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListProfilesParams is parameters of listProfiles operation.
type ListProfilesParams struct {
	// Год, для которого проверяется наличие уже
	// сгенерированного recap (влияет только на поле `recap` в
	// ответе). По умолчанию — предыдущий год.
	Year OptYear `json:",omitempty,omitzero"`
}

func unpackListProfilesParams(packed middleware.Parameters) (params ListProfilesParams) {
	{
		key := middleware.ParameterKey{
			Name: "year",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Year = v.(OptYear)
		}
	}
	return params
}

func decodeListProfilesParams(args [0]string, argsEscaped bool, r *http.Request) (params ListProfilesParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: year.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "year",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotYearVal Year
				if err := func() error {
					var paramsDotYearValVal int32
					if err := func() error {
						val, err := d.DecodeValue()
						if err != nil {
							return err
						}

						c, err := conv.ToInt32(val)
						if err != nil {
							return err
						}

						paramsDotYearValVal = c
						return nil
					}(); err != nil {
						return err
					}
					paramsDotYearVal = Year(paramsDotYearValVal)
					return nil
				}(); err != nil {
					return err
				}
				params.Year.SetTo(paramsDotYearVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Year.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "year",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// ShareRecapParams is parameters of shareRecap operation.
type ShareRecapParams struct {
	// Идентификатор recap.
	ID UUID
}

func unpackShareRecapParams(packed middleware.Parameters) (params ShareRecapParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(UUID)
	}
	return params
}

func decodeShareRecapParams(args [1]string, argsEscaped bool, r *http.Request) (params ShareRecapParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotIDVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ID = UUID(paramsDotIDVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
