// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateRecapOperation  OperationName = "CreateRecap"
	GetRecapOperation     OperationName = "GetRecap"
	ListProfilesOperation OperationName = "ListProfiles"
	ShareRecapOperation   OperationName = "ShareRecap"
)
