// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateRecap implements createRecap operation.
	//
	// Считает метрики профиля за год, определяет архетип и
	// собирает слайды. В ответе возвращается только
	// идентификатор — за самими слайдами клиент идёт в
	// `GET /recaps/{id}`.
	//
	// Операция идемпотентна по паре (`profileId`, `year`):
	//
	//  - если recap ещё не существует — `201 Created`;
	//  - если уже существует — `200 OK` с идентификатором ранее
	//    сгенерированного recap.
	//
	// POST /recaps
	CreateRecap(ctx context.Context, req *CreateRecapRequest) (CreateRecapRes, error)
	// GetRecap implements getRecap operation.
	//
	// Получить «Итоги года».
	//
	// GET /recaps/{id}
	GetRecap(ctx context.Context, params GetRecapParams) (GetRecapRes, error)
	// ListProfiles implements listProfiles operation.
	//
	// Возвращает набор заранее подготовленных профилей, на
	// которых демонстрируется работа генерации. Список
	// небольшой и постраничности не требует.
	//
	// GET /profiles
	ListProfiles(ctx context.Context, params ListProfilesParams) (ListProfilesRes, error)
	// ShareRecap implements shareRecap operation.
	//
	// Публикует урезанную версию итогов по постоянной
	// ссылке.
	//
	// В карточку попадают только безопасные агрегаты:
	// архетип, число активных дней, любимая категория,
	// бейджи и «мягкие» метрики. Никогда не попадают: суммы
	// сделок, конкретные объявления, сообщения и данные
	// контрагентов.
	//
	// Операция идемпотентна: повторный вызов для того же recap
	// возвращает ту же ссылку (`200 OK`), если карточка ещё не
	// отозвана.
	//
	// POST /recaps/{id}/share
	ShareRecap(ctx context.Context, req OptShareRecapRequest, params ShareRecapParams) (ShareRecapRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
