// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateRecap implements createRecap operation.
//
// Считает метрики профиля за год, определяет архетип и
// собирает слайды. В ответе возвращается только
// идентификатор — за самими слайдами клиент идёт в
// `GET /recaps/{id}`.
//
// Операция идемпотентна по паре (`profileId`, `year`):
//
//   - если recap ещё не существует — `201 Created`;
//   - если уже существует — `200 OK` с идентификатором ранее
//     сгенерированного recap.
//
// POST /recaps
func (UnimplementedHandler) CreateRecap(ctx context.Context, req *CreateRecapRequest) (r CreateRecapRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRecap implements getRecap operation.
//
// Получить «Итоги года».
//
// GET /recaps/{id}
func (UnimplementedHandler) GetRecap(ctx context.Context, params GetRecapParams) (r GetRecapRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListProfiles implements listProfiles operation.
//
// Возвращает набор заранее подготовленных профилей, на
// которых демонстрируется работа генерации. Список
// небольшой и постраничности не требует.
//
// GET /profiles
func (UnimplementedHandler) ListProfiles(ctx context.Context, params ListProfilesParams) (r ListProfilesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ShareRecap implements shareRecap operation.
//
// Публикует урезанную версию итогов по постоянной
// ссылке.
//
// В карточку попадают только безопасные агрегаты:
// архетип, число активных дней, любимая категория,
// бейджи и «мягкие» метрики. Никогда не попадают: суммы
// сделок, конкретные объявления, сообщения и данные
// контрагентов.
//
// Операция идемпотентна: повторный вызов для того же recap
// возвращает ту же ссылку (`200 OK`), если карточка ещё не
// отозвана.
//
// POST /recaps/{id}/share
func (UnimplementedHandler) ShareRecap(ctx context.Context, req OptShareRecapRequest, params ShareRecapParams) (r ShareRecapRes, _ error) {
	return r, ht.ErrNotImplemented
}
