// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *ShareRecapRequest) setDefaults() {
	{
		val := ShareRecapRequestTheme("dark")
		s.Theme.SetTo(val)
	}
}
