// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/url"
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

// Merged schema.
// Ref: #/components/schemas/ActiveDaysSlide
type ActiveDaysSlide struct {
	Type       RecapSlideType `json:"type"`
	Title      string         `json:"title"`
	Subtitle   OptString      `json:"subtitle"`
	Cta        OptNilCta      `json:"cta"`
	ActiveDays int32          `json:"activeDays"`
	// Процент пользователей, которых обошёл этот профиль.
	Percentile   OptInt32 `json:"percentile"`
	BusiestMonth OptInt32 `json:"busiestMonth"`
}

// GetType returns the value of Type.
func (s *ActiveDaysSlide) GetType() RecapSlideType {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *ActiveDaysSlide) GetTitle() string {
	return s.Title
}

// GetSubtitle returns the value of Subtitle.
func (s *ActiveDaysSlide) GetSubtitle() OptString {
	return s.Subtitle
}

// GetCta returns the value of Cta.
func (s *ActiveDaysSlide) GetCta() OptNilCta {
	return s.Cta
}

// GetActiveDays returns the value of ActiveDays.
func (s *ActiveDaysSlide) GetActiveDays() int32 {
	return s.ActiveDays
}

// GetPercentile returns the value of Percentile.
func (s *ActiveDaysSlide) GetPercentile() OptInt32 {
	return s.Percentile
}

// GetBusiestMonth returns the value of BusiestMonth.
func (s *ActiveDaysSlide) GetBusiestMonth() OptInt32 {
	return s.BusiestMonth
}

// SetType sets the value of Type.
func (s *ActiveDaysSlide) SetType(val RecapSlideType) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *ActiveDaysSlide) SetTitle(val string) {
	s.Title = val
}

// SetSubtitle sets the value of Subtitle.
func (s *ActiveDaysSlide) SetSubtitle(val OptString) {
	s.Subtitle = val
}

// SetCta sets the value of Cta.
func (s *ActiveDaysSlide) SetCta(val OptNilCta) {
	s.Cta = val
}

// SetActiveDays sets the value of ActiveDays.
func (s *ActiveDaysSlide) SetActiveDays(val int32) {
	s.ActiveDays = val
}

// SetPercentile sets the value of Percentile.
func (s *ActiveDaysSlide) SetPercentile(val OptInt32) {
	s.Percentile = val
}

// SetBusiestMonth sets the value of BusiestMonth.
func (s *ActiveDaysSlide) SetBusiestMonth(val OptInt32) {
	s.BusiestMonth = val
}

// Денежная величина в виде диапазона — точные суммы
// намеренно не раскрываются.
// Ref: #/components/schemas/AmountRange
type AmountRange struct {
	Min int64 `json:"min"`
	// `null` означает открытый верхний край диапазона.
	Max      NilInt64            `json:"max"`
	Currency AmountRangeCurrency `json:"currency"`
	Label    string              `json:"label"`
}

// GetMin returns the value of Min.
func (s *AmountRange) GetMin() int64 {
	return s.Min
}

// GetMax returns the value of Max.
func (s *AmountRange) GetMax() NilInt64 {
	return s.Max
}

// GetCurrency returns the value of Currency.
func (s *AmountRange) GetCurrency() AmountRangeCurrency {
	return s.Currency
}

// GetLabel returns the value of Label.
func (s *AmountRange) GetLabel() string {
	return s.Label
}

// SetMin sets the value of Min.
func (s *AmountRange) SetMin(val int64) {
	s.Min = val
}

// SetMax sets the value of Max.
func (s *AmountRange) SetMax(val NilInt64) {
	s.Max = val
}

// SetCurrency sets the value of Currency.
func (s *AmountRange) SetCurrency(val AmountRangeCurrency) {
	s.Currency = val
}

// SetLabel sets the value of Label.
func (s *AmountRange) SetLabel(val string) {
	s.Label = val
}

type AmountRangeCurrency string

const (
	AmountRangeCurrencyRUB AmountRangeCurrency = "RUB"
)

// AllValues returns all AmountRangeCurrency values.
func (AmountRangeCurrency) AllValues() []AmountRangeCurrency {
	return []AmountRangeCurrency{
		AmountRangeCurrencyRUB,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AmountRangeCurrency) MarshalText() ([]byte, error) {
	switch s {
	case AmountRangeCurrencyRUB:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AmountRangeCurrency) UnmarshalText(data []byte) error {
	switch AmountRangeCurrency(data) {
	case AmountRangeCurrencyRUB:
		*s = AmountRangeCurrencyRUB
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Тип поведения пользователя. Считается
// детерминированно из метрик, поэтому вместе с ним
// всегда отдаются `reasons` — прозрачное объяснение, почему
// пользователь получил именно этот архетип.
// Ref: #/components/schemas/Archetype
type Archetype struct {
	Code        ArchetypeCode `json:"code"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	// Метрики, повлиявшие на выбор архетипа.
	Reasons []ArchetypeReason `json:"reasons"`
}

// GetCode returns the value of Code.
func (s *Archetype) GetCode() ArchetypeCode {
	return s.Code
}

// GetTitle returns the value of Title.
func (s *Archetype) GetTitle() string {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *Archetype) GetDescription() string {
	return s.Description
}

// GetReasons returns the value of Reasons.
func (s *Archetype) GetReasons() []ArchetypeReason {
	return s.Reasons
}

// SetCode sets the value of Code.
func (s *Archetype) SetCode(val ArchetypeCode) {
	s.Code = val
}

// SetTitle sets the value of Title.
func (s *Archetype) SetTitle(val string) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *Archetype) SetDescription(val string) {
	s.Description = val
}

// SetReasons sets the value of Reasons.
func (s *Archetype) SetReasons(val []ArchetypeReason) {
	s.Reasons = val
}

type ArchetypeCode string

const (
	ArchetypeCodeTreasureHunter ArchetypeCode = "treasure_hunter"
	ArchetypeCodeCollector      ArchetypeCode = "collector"
	ArchetypeCodeDealmaker      ArchetypeCode = "dealmaker"
	ArchetypeCodeNegotiator     ArchetypeCode = "negotiator"
	ArchetypeCodeMinimalist     ArchetypeCode = "minimalist"
	ArchetypeCodeExplorer       ArchetypeCode = "explorer"
)

// AllValues returns all ArchetypeCode values.
func (ArchetypeCode) AllValues() []ArchetypeCode {
	return []ArchetypeCode{
		ArchetypeCodeTreasureHunter,
		ArchetypeCodeCollector,
		ArchetypeCodeDealmaker,
		ArchetypeCodeNegotiator,
		ArchetypeCodeMinimalist,
		ArchetypeCodeExplorer,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ArchetypeCode) MarshalText() ([]byte, error) {
	switch s {
	case ArchetypeCodeTreasureHunter:
		return []byte(s), nil
	case ArchetypeCodeCollector:
		return []byte(s), nil
	case ArchetypeCodeDealmaker:
		return []byte(s), nil
	case ArchetypeCodeNegotiator:
		return []byte(s), nil
	case ArchetypeCodeMinimalist:
		return []byte(s), nil
	case ArchetypeCodeExplorer:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ArchetypeCode) UnmarshalText(data []byte) error {
	switch ArchetypeCode(data) {
	case ArchetypeCodeTreasureHunter:
		*s = ArchetypeCodeTreasureHunter
		return nil
	case ArchetypeCodeCollector:
		*s = ArchetypeCodeCollector
		return nil
	case ArchetypeCodeDealmaker:
		*s = ArchetypeCodeDealmaker
		return nil
	case ArchetypeCodeNegotiator:
		*s = ArchetypeCodeNegotiator
		return nil
	case ArchetypeCodeMinimalist:
		*s = ArchetypeCodeMinimalist
		return nil
	case ArchetypeCodeExplorer:
		*s = ArchetypeCodeExplorer
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ArchetypeReason
type ArchetypeReason struct {
	Metric MetricCode `json:"metric"`
	// Значение метрики в человекочитаемом виде.
	Value       OptString `json:"value"`
	Explanation string    `json:"explanation"`
}

// GetMetric returns the value of Metric.
func (s *ArchetypeReason) GetMetric() MetricCode {
	return s.Metric
}

// GetValue returns the value of Value.
func (s *ArchetypeReason) GetValue() OptString {
	return s.Value
}

// GetExplanation returns the value of Explanation.
func (s *ArchetypeReason) GetExplanation() string {
	return s.Explanation
}

// SetMetric sets the value of Metric.
func (s *ArchetypeReason) SetMetric(val MetricCode) {
	s.Metric = val
}

// SetValue sets the value of Value.
func (s *ArchetypeReason) SetValue(val OptString) {
	s.Value = val
}

// SetExplanation sets the value of Explanation.
func (s *ArchetypeReason) SetExplanation(val string) {
	s.Explanation = val
}

// Merged schema.
// Ref: #/components/schemas/ArchetypeSlide
type ArchetypeSlide struct {
	Type      RecapSlideType `json:"type"`
	Title     string         `json:"title"`
	Subtitle  OptString      `json:"subtitle"`
	Cta       OptNilCta      `json:"cta"`
	Archetype Archetype      `json:"archetype"`
}

// GetType returns the value of Type.
func (s *ArchetypeSlide) GetType() RecapSlideType {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *ArchetypeSlide) GetTitle() string {
	return s.Title
}

// GetSubtitle returns the value of Subtitle.
func (s *ArchetypeSlide) GetSubtitle() OptString {
	return s.Subtitle
}

// GetCta returns the value of Cta.
func (s *ArchetypeSlide) GetCta() OptNilCta {
	return s.Cta
}

// GetArchetype returns the value of Archetype.
func (s *ArchetypeSlide) GetArchetype() Archetype {
	return s.Archetype
}

// SetType sets the value of Type.
func (s *ArchetypeSlide) SetType(val RecapSlideType) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *ArchetypeSlide) SetTitle(val string) {
	s.Title = val
}

// SetSubtitle sets the value of Subtitle.
func (s *ArchetypeSlide) SetSubtitle(val OptString) {
	s.Subtitle = val
}

// SetCta sets the value of Cta.
func (s *ArchetypeSlide) SetCta(val OptNilCta) {
	s.Cta = val
}

// SetArchetype sets the value of Archetype.
func (s *ArchetypeSlide) SetArchetype(val Archetype) {
	s.Archetype = val
}

// Ачивка, выданная по правилам генерации.
// Ref: #/components/schemas/Badge
type Badge struct {
	Code        string        `json:"code"`
	Title       string        `json:"title"`
	Description OptString     `json:"description"`
	IconUrl     OptNilURI     `json:"iconUrl"`
	Level       OptBadgeLevel `json:"level"`
}

// GetCode returns the value of Code.
func (s *Badge) GetCode() string {
	return s.Code
}

// GetTitle returns the value of Title.
func (s *Badge) GetTitle() string {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *Badge) GetDescription() OptString {
	return s.Description
}

// GetIconUrl returns the value of IconUrl.
func (s *Badge) GetIconUrl() OptNilURI {
	return s.IconUrl
}

// GetLevel returns the value of Level.
func (s *Badge) GetLevel() OptBadgeLevel {
	return s.Level
}

// SetCode sets the value of Code.
func (s *Badge) SetCode(val string) {
	s.Code = val
}

// SetTitle sets the value of Title.
func (s *Badge) SetTitle(val string) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *Badge) SetDescription(val OptString) {
	s.Description = val
}

// SetIconUrl sets the value of IconUrl.
func (s *Badge) SetIconUrl(val OptNilURI) {
	s.IconUrl = val
}

// SetLevel sets the value of Level.
func (s *Badge) SetLevel(val OptBadgeLevel) {
	s.Level = val
}

type BadgeLevel string

const (
	BadgeLevelBronze BadgeLevel = "bronze"
	BadgeLevelSilver BadgeLevel = "silver"
	BadgeLevelGold   BadgeLevel = "gold"
)

// AllValues returns all BadgeLevel values.
func (BadgeLevel) AllValues() []BadgeLevel {
	return []BadgeLevel{
		BadgeLevelBronze,
		BadgeLevelSilver,
		BadgeLevelGold,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s BadgeLevel) MarshalText() ([]byte, error) {
	switch s {
	case BadgeLevelBronze:
		return []byte(s), nil
	case BadgeLevelSilver:
		return []byte(s), nil
	case BadgeLevelGold:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *BadgeLevel) UnmarshalText(data []byte) error {
	switch BadgeLevel(data) {
	case BadgeLevelBronze:
		*s = BadgeLevelBronze
		return nil
	case BadgeLevelSilver:
		*s = BadgeLevelSilver
		return nil
	case BadgeLevelGold:
		*s = BadgeLevelGold
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/CategoryRef
type CategoryRef struct {
	ID    UUID   `json:"id"`
	Title string `json:"title"`
}

// GetID returns the value of ID.
func (s *CategoryRef) GetID() UUID {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *CategoryRef) GetTitle() string {
	return s.Title
}

// SetID sets the value of ID.
func (s *CategoryRef) SetID(val UUID) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *CategoryRef) SetTitle(val string) {
	s.Title = val
}

// Merged schema.
// Ref: #/components/schemas/CategorySlide
type CategorySlide struct {
	Type        RecapSlideType    `json:"type"`
	Title       string            `json:"title"`
	Subtitle    OptString         `json:"subtitle"`
	Cta         OptNilCta         `json:"cta"`
	Category    CategoryRef       `json:"category"`
	Subcategory OptNilCategoryRef `json:"subcategory"`
	// Доля активности в этой категории, %.
	Share OptInt32 `json:"share"`
	// Свежие объявления из любимой категории.
	Recommendations []ListingRef `json:"recommendations"`
}

// GetType returns the value of Type.
func (s *CategorySlide) GetType() RecapSlideType {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *CategorySlide) GetTitle() string {
	return s.Title
}

// GetSubtitle returns the value of Subtitle.
func (s *CategorySlide) GetSubtitle() OptString {
	return s.Subtitle
}

// GetCta returns the value of Cta.
func (s *CategorySlide) GetCta() OptNilCta {
	return s.Cta
}

// GetCategory returns the value of Category.
func (s *CategorySlide) GetCategory() CategoryRef {
	return s.Category
}

// GetSubcategory returns the value of Subcategory.
func (s *CategorySlide) GetSubcategory() OptNilCategoryRef {
	return s.Subcategory
}

// GetShare returns the value of Share.
func (s *CategorySlide) GetShare() OptInt32 {
	return s.Share
}

// GetRecommendations returns the value of Recommendations.
func (s *CategorySlide) GetRecommendations() []ListingRef {
	return s.Recommendations
}

// SetType sets the value of Type.
func (s *CategorySlide) SetType(val RecapSlideType) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *CategorySlide) SetTitle(val string) {
	s.Title = val
}

// SetSubtitle sets the value of Subtitle.
func (s *CategorySlide) SetSubtitle(val OptString) {
	s.Subtitle = val
}

// SetCta sets the value of Cta.
func (s *CategorySlide) SetCta(val OptNilCta) {
	s.Cta = val
}

// SetCategory sets the value of Category.
func (s *CategorySlide) SetCategory(val CategoryRef) {
	s.Category = val
}

// SetSubcategory sets the value of Subcategory.
func (s *CategorySlide) SetSubcategory(val OptNilCategoryRef) {
	s.Subcategory = val
}

// SetShare sets the value of Share.
func (s *CategorySlide) SetShare(val OptInt32) {
	s.Share = val
}

// SetRecommendations sets the value of Recommendations.
func (s *CategorySlide) SetRecommendations(val []ListingRef) {
	s.Recommendations = val
}

type CreateRecapBadRequest Error

func (*CreateRecapBadRequest) createRecapRes() {}

type CreateRecapConflict Error

func (*CreateRecapConflict) createRecapRes() {}

type CreateRecapCreated CreateRecapResponse

func (*CreateRecapCreated) createRecapRes() {}

type CreateRecapInternalServerError Error

func (*CreateRecapInternalServerError) createRecapRes() {}

type CreateRecapNotFound Error

func (*CreateRecapNotFound) createRecapRes() {}

type CreateRecapOK CreateRecapResponse

func (*CreateRecapOK) createRecapRes() {}

// Ref: #/components/schemas/CreateRecapRequest
type CreateRecapRequest struct {
	ProfileId UUID `json:"profileId"`
	Year      Year `json:"year"`
}

// GetProfileId returns the value of ProfileId.
func (s *CreateRecapRequest) GetProfileId() UUID {
	return s.ProfileId
}

// GetYear returns the value of Year.
func (s *CreateRecapRequest) GetYear() Year {
	return s.Year
}

// SetProfileId sets the value of ProfileId.
func (s *CreateRecapRequest) SetProfileId(val UUID) {
	s.ProfileId = val
}

// SetYear sets the value of Year.
func (s *CreateRecapRequest) SetYear(val Year) {
	s.Year = val
}

// Ref: #/components/schemas/CreateRecapResponse
type CreateRecapResponse struct {
	ID UUID `json:"id"`
}

// GetID returns the value of ID.
func (s *CreateRecapResponse) GetID() UUID {
	return s.ID
}

// SetID sets the value of ID.
func (s *CreateRecapResponse) SetID(val UUID) {
	s.ID = val
}

type CreateRecapUnprocessableEntity Error

func (*CreateRecapUnprocessableEntity) createRecapRes() {}

// Следующее действие, которое предлагается
// пользователю после слайда.
// Ref: #/components/schemas/Cta
type Cta struct {
	Action CtaAction `json:"action"`
	Title  string    `json:"title"`
	// Заполняется для `open_listing`.
	ListingId OptNilUUID `json:"listingId"`
	// Заполняется для `open_category`.
	CategoryId OptNilUUID   `json:"categoryId"`
	URL        OptNilString `json:"url"`
}

// GetAction returns the value of Action.
func (s *Cta) GetAction() CtaAction {
	return s.Action
}

// GetTitle returns the value of Title.
func (s *Cta) GetTitle() string {
	return s.Title
}

// GetListingId returns the value of ListingId.
func (s *Cta) GetListingId() OptNilUUID {
	return s.ListingId
}

// GetCategoryId returns the value of CategoryId.
func (s *Cta) GetCategoryId() OptNilUUID {
	return s.CategoryId
}

// GetURL returns the value of URL.
func (s *Cta) GetURL() OptNilString {
	return s.URL
}

// SetAction sets the value of Action.
func (s *Cta) SetAction(val CtaAction) {
	s.Action = val
}

// SetTitle sets the value of Title.
func (s *Cta) SetTitle(val string) {
	s.Title = val
}

// SetListingId sets the value of ListingId.
func (s *Cta) SetListingId(val OptNilUUID) {
	s.ListingId = val
}

// SetCategoryId sets the value of CategoryId.
func (s *Cta) SetCategoryId(val OptNilUUID) {
	s.CategoryId = val
}

// SetURL sets the value of URL.
func (s *Cta) SetURL(val OptNilString) {
	s.URL = val
}

type CtaAction string

const (
	CtaActionOpenListing   CtaAction = "open_listing"
	CtaActionOpenCategory  CtaAction = "open_category"
	CtaActionOpenFavorites CtaAction = "open_favorites"
	CtaActionCreateListing CtaAction = "create_listing"
	CtaActionShareRecap    CtaAction = "share_recap"
)

// AllValues returns all CtaAction values.
func (CtaAction) AllValues() []CtaAction {
	return []CtaAction{
		CtaActionOpenListing,
		CtaActionOpenCategory,
		CtaActionOpenFavorites,
		CtaActionCreateListing,
		CtaActionShareRecap,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CtaAction) MarshalText() ([]byte, error) {
	switch s {
	case CtaActionOpenListing:
		return []byte(s), nil
	case CtaActionOpenCategory:
		return []byte(s), nil
	case CtaActionOpenFavorites:
		return []byte(s), nil
	case CtaActionCreateListing:
		return []byte(s), nil
	case CtaActionShareRecap:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CtaAction) UnmarshalText(data []byte) error {
	switch CtaAction(data) {
	case CtaActionOpenListing:
		*s = CtaActionOpenListing
		return nil
	case CtaActionOpenCategory:
		*s = CtaActionOpenCategory
		return nil
	case CtaActionOpenFavorites:
		*s = CtaActionOpenFavorites
		return nil
	case CtaActionCreateListing:
		*s = CtaActionCreateListing
		return nil
	case CtaActionShareRecap:
		*s = CtaActionShareRecap
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Error
type Error struct {
	Code ErrorCode `json:"code"`
	// Пояснение для разработчика: логи, отладка, Sentry. Не
	// предназначено для показа пользователю — текст в UI
	// фронт подбирает сам по значению `code`.
	Message string `json:"message"`
	// Идентификатор запроса для поиска в логах.
	RequestId OptUUID `json:"requestId"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() ErrorCode {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// GetRequestId returns the value of RequestId.
func (s *Error) GetRequestId() OptUUID {
	return s.RequestId
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val ErrorCode) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// SetRequestId sets the value of RequestId.
func (s *Error) SetRequestId(val OptUUID) {
	s.RequestId = val
}

// Машиночитаемый код ошибки:
//
//   - `bad_request` — невалидный JSON, типы или формат
//     идентификатора;
//   - `validation_error` — значения полей вне допустимых границ;
//   - `profile_not_found` — профиль не существует;
//   - `recap_not_found` — recap не существует;
//   - `not_enough_activity` — за год недостаточно активности для
//     генерации;
//   - `recap_not_ready` — recap ещё в статусе `generating` или `failed`;
//   - `rate_limited` — превышен лимит запросов;
//   - `internal_error` — необработанная ошибка сервиса.
//
// Ref: #/components/schemas/ErrorCode
type ErrorCode string

const (
	ErrorCodeBadRequest        ErrorCode = "bad_request"
	ErrorCodeValidationError   ErrorCode = "validation_error"
	ErrorCodeProfileNotFound   ErrorCode = "profile_not_found"
	ErrorCodeRecapNotFound     ErrorCode = "recap_not_found"
	ErrorCodeNotEnoughActivity ErrorCode = "not_enough_activity"
	ErrorCodeRecapNotReady     ErrorCode = "recap_not_ready"
	ErrorCodeRateLimited       ErrorCode = "rate_limited"
	ErrorCodeInternalError     ErrorCode = "internal_error"
)

// AllValues returns all ErrorCode values.
func (ErrorCode) AllValues() []ErrorCode {
	return []ErrorCode{
		ErrorCodeBadRequest,
		ErrorCodeValidationError,
		ErrorCodeProfileNotFound,
		ErrorCodeRecapNotFound,
		ErrorCodeNotEnoughActivity,
		ErrorCodeRecapNotReady,
		ErrorCodeRateLimited,
		ErrorCodeInternalError,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ErrorCode) MarshalText() ([]byte, error) {
	switch s {
	case ErrorCodeBadRequest:
		return []byte(s), nil
	case ErrorCodeValidationError:
		return []byte(s), nil
	case ErrorCodeProfileNotFound:
		return []byte(s), nil
	case ErrorCodeRecapNotFound:
		return []byte(s), nil
	case ErrorCodeNotEnoughActivity:
		return []byte(s), nil
	case ErrorCodeRecapNotReady:
		return []byte(s), nil
	case ErrorCodeRateLimited:
		return []byte(s), nil
	case ErrorCodeInternalError:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ErrorCode) UnmarshalText(data []byte) error {
	switch ErrorCode(data) {
	case ErrorCodeBadRequest:
		*s = ErrorCodeBadRequest
		return nil
	case ErrorCodeValidationError:
		*s = ErrorCodeValidationError
		return nil
	case ErrorCodeProfileNotFound:
		*s = ErrorCodeProfileNotFound
		return nil
	case ErrorCodeRecapNotFound:
		*s = ErrorCodeRecapNotFound
		return nil
	case ErrorCodeNotEnoughActivity:
		*s = ErrorCodeNotEnoughActivity
		return nil
	case ErrorCodeRecapNotReady:
		*s = ErrorCodeRecapNotReady
		return nil
	case ErrorCodeRateLimited:
		*s = ErrorCodeRateLimited
		return nil
	case ErrorCodeInternalError:
		*s = ErrorCodeInternalError
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Merged schema.
// Ref: #/components/schemas/FavoritesSlide
type FavoritesSlide struct {
	Type      RecapSlideType `json:"type"`
	Title     string         `json:"title"`
	Subtitle  OptString      `json:"subtitle"`
	Cta       OptNilCta      `json:"cta"`
	Favorites int64          `json:"favorites"`
	// Объявление, которое дольше всех лежит в избранном —
	// повод вернуться к нему.
	OldestFavorite OptNilListingRef `json:"oldestFavorite"`
	// Сколько избранных объявлений всё ещё активны.
	StillAvailable OptInt32 `json:"stillAvailable"`
}

// GetType returns the value of Type.
func (s *FavoritesSlide) GetType() RecapSlideType {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *FavoritesSlide) GetTitle() string {
	return s.Title
}

// GetSubtitle returns the value of Subtitle.
func (s *FavoritesSlide) GetSubtitle() OptString {
	return s.Subtitle
}

// GetCta returns the value of Cta.
func (s *FavoritesSlide) GetCta() OptNilCta {
	return s.Cta
}

// GetFavorites returns the value of Favorites.
func (s *FavoritesSlide) GetFavorites() int64 {
	return s.Favorites
}

// GetOldestFavorite returns the value of OldestFavorite.
func (s *FavoritesSlide) GetOldestFavorite() OptNilListingRef {
	return s.OldestFavorite
}

// GetStillAvailable returns the value of StillAvailable.
func (s *FavoritesSlide) GetStillAvailable() OptInt32 {
	return s.StillAvailable
}

// SetType sets the value of Type.
func (s *FavoritesSlide) SetType(val RecapSlideType) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *FavoritesSlide) SetTitle(val string) {
	s.Title = val
}

// SetSubtitle sets the value of Subtitle.
func (s *FavoritesSlide) SetSubtitle(val OptString) {
	s.Subtitle = val
}

// SetCta sets the value of Cta.
func (s *FavoritesSlide) SetCta(val OptNilCta) {
	s.Cta = val
}

// SetFavorites sets the value of Favorites.
func (s *FavoritesSlide) SetFavorites(val int64) {
	s.Favorites = val
}

// SetOldestFavorite sets the value of OldestFavorite.
func (s *FavoritesSlide) SetOldestFavorite(val OptNilListingRef) {
	s.OldestFavorite = val
}

// SetStillAvailable sets the value of StillAvailable.
func (s *FavoritesSlide) SetStillAvailable(val OptInt32) {
	s.StillAvailable = val
}

// Merged schema.
// Ref: #/components/schemas/FinalSlide
type FinalSlide struct {
	Type     RecapSlideType `json:"type"`
	Title    string         `json:"title"`
	Subtitle OptString      `json:"subtitle"`
	Cta      OptNilCta      `json:"cta"`
	Badges   []Badge        `json:"badges"`
	// Что предлагается сделать после просмотра итогов.
	Actions []Cta `json:"actions"`
}

// GetType returns the value of Type.
func (s *FinalSlide) GetType() RecapSlideType {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *FinalSlide) GetTitle() string {
	return s.Title
}

// GetSubtitle returns the value of Subtitle.
func (s *FinalSlide) GetSubtitle() OptString {
	return s.Subtitle
}

// GetCta returns the value of Cta.
func (s *FinalSlide) GetCta() OptNilCta {
	return s.Cta
}

// GetBadges returns the value of Badges.
func (s *FinalSlide) GetBadges() []Badge {
	return s.Badges
}

// GetActions returns the value of Actions.
func (s *FinalSlide) GetActions() []Cta {
	return s.Actions
}

// SetType sets the value of Type.
func (s *FinalSlide) SetType(val RecapSlideType) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *FinalSlide) SetTitle(val string) {
	s.Title = val
}

// SetSubtitle sets the value of Subtitle.
func (s *FinalSlide) SetSubtitle(val OptString) {
	s.Subtitle = val
}

// SetCta sets the value of Cta.
func (s *FinalSlide) SetCta(val OptNilCta) {
	s.Cta = val
}

// SetBadges sets the value of Badges.
func (s *FinalSlide) SetBadges(val []Badge) {
	s.Badges = val
}

// SetActions sets the value of Actions.
func (s *FinalSlide) SetActions(val []Cta) {
	s.Actions = val
}

type GetRecapBadRequest Error

func (*GetRecapBadRequest) getRecapRes() {}

type GetRecapInternalServerError Error

func (*GetRecapInternalServerError) getRecapRes() {}

type GetRecapNotFound Error

func (*GetRecapNotFound) getRecapRes() {}

// Merged schema.
// Ref: #/components/schemas/InterestsSlide
type InterestsSlide struct {
	Type     RecapSlideType `json:"type"`
	Title    string         `json:"title"`
	Subtitle OptString      `json:"subtitle"`
	Cta      OptNilCta      `json:"cta"`
	// Как менялись интересы в течение года.
	Periods      []PeriodInterest `json:"periods"`
	ShiftSummary OptString        `json:"shiftSummary"`
}

// GetType returns the value of Type.
func (s *InterestsSlide) GetType() RecapSlideType {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *InterestsSlide) GetTitle() string {
	return s.Title
}

// GetSubtitle returns the value of Subtitle.
func (s *InterestsSlide) GetSubtitle() OptString {
	return s.Subtitle
}

// GetCta returns the value of Cta.
func (s *InterestsSlide) GetCta() OptNilCta {
	return s.Cta
}

// GetPeriods returns the value of Periods.
func (s *InterestsSlide) GetPeriods() []PeriodInterest {
	return s.Periods
}

// GetShiftSummary returns the value of ShiftSummary.
func (s *InterestsSlide) GetShiftSummary() OptString {
	return s.ShiftSummary
}

// SetType sets the value of Type.
func (s *InterestsSlide) SetType(val RecapSlideType) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *InterestsSlide) SetTitle(val string) {
	s.Title = val
}

// SetSubtitle sets the value of Subtitle.
func (s *InterestsSlide) SetSubtitle(val OptString) {
	s.Subtitle = val
}

// SetCta sets the value of Cta.
func (s *InterestsSlide) SetCta(val OptNilCta) {
	s.Cta = val
}

// SetPeriods sets the value of Periods.
func (s *InterestsSlide) SetPeriods(val []PeriodInterest) {
	s.Periods = val
}

// SetShiftSummary sets the value of ShiftSummary.
func (s *InterestsSlide) SetShiftSummary(val OptString) {
	s.ShiftSummary = val
}

// Merged schema.
// Ref: #/components/schemas/IntroSlide
type IntroSlide struct {
	Type     RecapSlideType `json:"type"`
	Title    string         `json:"title"`
	Subtitle OptString      `json:"subtitle"`
	Cta      OptNilCta      `json:"cta"`
	Year     OptYear        `json:"year"`
}

// GetType returns the value of Type.
func (s *IntroSlide) GetType() RecapSlideType {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *IntroSlide) GetTitle() string {
	return s.Title
}

// GetSubtitle returns the value of Subtitle.
func (s *IntroSlide) GetSubtitle() OptString {
	return s.Subtitle
}

// GetCta returns the value of Cta.
func (s *IntroSlide) GetCta() OptNilCta {
	return s.Cta
}

// GetYear returns the value of Year.
func (s *IntroSlide) GetYear() OptYear {
	return s.Year
}

// SetType sets the value of Type.
func (s *IntroSlide) SetType(val RecapSlideType) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *IntroSlide) SetTitle(val string) {
	s.Title = val
}

// SetSubtitle sets the value of Subtitle.
func (s *IntroSlide) SetSubtitle(val OptString) {
	s.Subtitle = val
}

// SetCta sets the value of Cta.
func (s *IntroSlide) SetCta(val OptNilCta) {
	s.Cta = val
}

// SetYear sets the value of Year.
func (s *IntroSlide) SetYear(val OptYear) {
	s.Year = val
}

type ListProfilesBadRequest Error

func (*ListProfilesBadRequest) listProfilesRes() {}

type ListProfilesInternalServerError Error

func (*ListProfilesInternalServerError) listProfilesRes() {}

type ListProfilesOK struct {
	Items []Profile `json:"items"`
}

// GetItems returns the value of Items.
func (s *ListProfilesOK) GetItems() []Profile {
	return s.Items
}

// SetItems sets the value of Items.
func (s *ListProfilesOK) SetItems(val []Profile) {
	s.Items = val
}

func (*ListProfilesOK) listProfilesRes() {}

// Ref: #/components/schemas/ListingRef
type ListingRef struct {
	ID         UUID        `json:"id"`
	Title      string      `json:"title"`
	Price      OptNilInt64 `json:"price"`
	ImageUrl   OptNilURI   `json:"imageUrl"`
	CategoryId OptUUID     `json:"categoryId"`
	// Когда объявление попало в избранное.
	AddedAt OptDateTime `json:"addedAt"`
}

// GetID returns the value of ID.
func (s *ListingRef) GetID() UUID {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *ListingRef) GetTitle() string {
	return s.Title
}

// GetPrice returns the value of Price.
func (s *ListingRef) GetPrice() OptNilInt64 {
	return s.Price
}

// GetImageUrl returns the value of ImageUrl.
func (s *ListingRef) GetImageUrl() OptNilURI {
	return s.ImageUrl
}

// GetCategoryId returns the value of CategoryId.
func (s *ListingRef) GetCategoryId() OptUUID {
	return s.CategoryId
}

// GetAddedAt returns the value of AddedAt.
func (s *ListingRef) GetAddedAt() OptDateTime {
	return s.AddedAt
}

// SetID sets the value of ID.
func (s *ListingRef) SetID(val UUID) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *ListingRef) SetTitle(val string) {
	s.Title = val
}

// SetPrice sets the value of Price.
func (s *ListingRef) SetPrice(val OptNilInt64) {
	s.Price = val
}

// SetImageUrl sets the value of ImageUrl.
func (s *ListingRef) SetImageUrl(val OptNilURI) {
	s.ImageUrl = val
}

// SetCategoryId sets the value of CategoryId.
func (s *ListingRef) SetCategoryId(val OptUUID) {
	s.CategoryId = val
}

// SetAddedAt sets the value of AddedAt.
func (s *ListingRef) SetAddedAt(val OptDateTime) {
	s.AddedAt = val
}

// Merged schema.
// Ref: #/components/schemas/MessagesSlide
type MessagesSlide struct {
	Type     RecapSlideType `json:"type"`
	Title    string         `json:"title"`
	Subtitle OptString      `json:"subtitle"`
	Cta      OptNilCta      `json:"cta"`
	// Количество сообщений. Содержимое переписок не
	// раскрывается никогда.
	Messages int64    `json:"messages"`
	Chats    OptInt32 `json:"chats"`
	// Доля сообщений, отправленных в роли покупателя, %.
	AsBuyerShare OptInt32 `json:"asBuyerShare"`
}

// GetType returns the value of Type.
func (s *MessagesSlide) GetType() RecapSlideType {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *MessagesSlide) GetTitle() string {
	return s.Title
}

// GetSubtitle returns the value of Subtitle.
func (s *MessagesSlide) GetSubtitle() OptString {
	return s.Subtitle
}

// GetCta returns the value of Cta.
func (s *MessagesSlide) GetCta() OptNilCta {
	return s.Cta
}

// GetMessages returns the value of Messages.
func (s *MessagesSlide) GetMessages() int64 {
	return s.Messages
}

// GetChats returns the value of Chats.
func (s *MessagesSlide) GetChats() OptInt32 {
	return s.Chats
}

// GetAsBuyerShare returns the value of AsBuyerShare.
func (s *MessagesSlide) GetAsBuyerShare() OptInt32 {
	return s.AsBuyerShare
}

// SetType sets the value of Type.
func (s *MessagesSlide) SetType(val RecapSlideType) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *MessagesSlide) SetTitle(val string) {
	s.Title = val
}

// SetSubtitle sets the value of Subtitle.
func (s *MessagesSlide) SetSubtitle(val OptString) {
	s.Subtitle = val
}

// SetCta sets the value of Cta.
func (s *MessagesSlide) SetCta(val OptNilCta) {
	s.Cta = val
}

// SetMessages sets the value of Messages.
func (s *MessagesSlide) SetMessages(val int64) {
	s.Messages = val
}

// SetChats sets the value of Chats.
func (s *MessagesSlide) SetChats(val OptInt32) {
	s.Chats = val
}

// SetAsBuyerShare sets the value of AsBuyerShare.
func (s *MessagesSlide) SetAsBuyerShare(val OptInt32) {
	s.AsBuyerShare = val
}

// Ref: #/components/schemas/MetricCode
type MetricCode string

const (
	MetricCodeActiveDays       MetricCode = "active_days"
	MetricCodeViews            MetricCode = "views"
	MetricCodeFavorites        MetricCode = "favorites"
	MetricCodeFavoriteCategory MetricCode = "favorite_category"
	MetricCodePurchases        MetricCode = "purchases"
	MetricCodeSales            MetricCode = "sales"
	MetricCodeMessages         MetricCode = "messages"
	MetricCodeInterestsShift   MetricCode = "interests_shift"
)

// AllValues returns all MetricCode values.
func (MetricCode) AllValues() []MetricCode {
	return []MetricCode{
		MetricCodeActiveDays,
		MetricCodeViews,
		MetricCodeFavorites,
		MetricCodeFavoriteCategory,
		MetricCodePurchases,
		MetricCodeSales,
		MetricCodeMessages,
		MetricCodeInterestsShift,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s MetricCode) MarshalText() ([]byte, error) {
	switch s {
	case MetricCodeActiveDays:
		return []byte(s), nil
	case MetricCodeViews:
		return []byte(s), nil
	case MetricCodeFavorites:
		return []byte(s), nil
	case MetricCodeFavoriteCategory:
		return []byte(s), nil
	case MetricCodePurchases:
		return []byte(s), nil
	case MetricCodeSales:
		return []byte(s), nil
	case MetricCodeMessages:
		return []byte(s), nil
	case MetricCodeInterestsShift:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *MetricCode) UnmarshalText(data []byte) error {
	switch MetricCode(data) {
	case MetricCodeActiveDays:
		*s = MetricCodeActiveDays
		return nil
	case MetricCodeViews:
		*s = MetricCodeViews
		return nil
	case MetricCodeFavorites:
		*s = MetricCodeFavorites
		return nil
	case MetricCodeFavoriteCategory:
		*s = MetricCodeFavoriteCategory
		return nil
	case MetricCodePurchases:
		*s = MetricCodePurchases
		return nil
	case MetricCodeSales:
		*s = MetricCodeSales
		return nil
	case MetricCodeMessages:
		*s = MetricCodeMessages
		return nil
	case MetricCodeInterestsShift:
		*s = MetricCodeInterestsShift
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewNilInt64 returns new NilInt64 with value set to v.
func NewNilInt64(v int64) NilInt64 {
	return NilInt64{
		Value: v,
	}
}

// NilInt64 is nullable int64.
type NilInt64 struct {
	Value int64
	Null  bool
}

// SetTo sets value to v.
func (o *NilInt64) SetTo(v int64) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilInt64) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilInt64) SetToNull() {
	o.Null = true
	var v int64
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilInt64) Get() (v int64, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptBadgeLevel returns new OptBadgeLevel with value set to v.
func NewOptBadgeLevel(v BadgeLevel) OptBadgeLevel {
	return OptBadgeLevel{
		Value: v,
		Set:   true,
	}
}

// OptBadgeLevel is optional BadgeLevel.
type OptBadgeLevel struct {
	Value BadgeLevel
	Set   bool
}

// IsSet returns true if OptBadgeLevel was set.
func (o OptBadgeLevel) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBadgeLevel) Reset() {
	var v BadgeLevel
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBadgeLevel) SetTo(v BadgeLevel) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBadgeLevel) Get() (v BadgeLevel, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBadgeLevel) Or(d BadgeLevel) BadgeLevel {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilAmountRange returns new OptNilAmountRange with value set to v.
func NewOptNilAmountRange(v AmountRange) OptNilAmountRange {
	return OptNilAmountRange{
		Value: v,
		Set:   true,
	}
}

// OptNilAmountRange is optional nullable AmountRange.
type OptNilAmountRange struct {
	Value AmountRange
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilAmountRange was set.
func (o OptNilAmountRange) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilAmountRange) Reset() {
	var v AmountRange
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilAmountRange) SetTo(v AmountRange) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilAmountRange) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilAmountRange) SetToNull() {
	o.Set = true
	o.Null = true
	var v AmountRange
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilAmountRange) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilAmountRange) Get() (v AmountRange, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilAmountRange) Or(d AmountRange) AmountRange {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilBadge returns new OptNilBadge with value set to v.
func NewOptNilBadge(v Badge) OptNilBadge {
	return OptNilBadge{
		Value: v,
		Set:   true,
	}
}

// OptNilBadge is optional nullable Badge.
type OptNilBadge struct {
	Value Badge
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilBadge was set.
func (o OptNilBadge) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilBadge) Reset() {
	var v Badge
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilBadge) SetTo(v Badge) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilBadge) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilBadge) SetToNull() {
	o.Set = true
	o.Null = true
	var v Badge
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilBadge) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilBadge) Get() (v Badge, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilBadge) Or(d Badge) Badge {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilCategoryRef returns new OptNilCategoryRef with value set to v.
func NewOptNilCategoryRef(v CategoryRef) OptNilCategoryRef {
	return OptNilCategoryRef{
		Value: v,
		Set:   true,
	}
}

// OptNilCategoryRef is optional nullable CategoryRef.
type OptNilCategoryRef struct {
	Value CategoryRef
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilCategoryRef was set.
func (o OptNilCategoryRef) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilCategoryRef) Reset() {
	var v CategoryRef
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilCategoryRef) SetTo(v CategoryRef) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilCategoryRef) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilCategoryRef) SetToNull() {
	o.Set = true
	o.Null = true
	var v CategoryRef
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilCategoryRef) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilCategoryRef) Get() (v CategoryRef, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilCategoryRef) Or(d CategoryRef) CategoryRef {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilCta returns new OptNilCta with value set to v.
func NewOptNilCta(v Cta) OptNilCta {
	return OptNilCta{
		Value: v,
		Set:   true,
	}
}

// OptNilCta is optional nullable Cta.
type OptNilCta struct {
	Value Cta
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilCta was set.
func (o OptNilCta) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilCta) Reset() {
	var v Cta
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilCta) SetTo(v Cta) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilCta) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilCta) SetToNull() {
	o.Set = true
	o.Null = true
	var v Cta
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilCta) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilCta) Get() (v Cta, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilCta) Or(d Cta) Cta {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilDateTime returns new OptNilDateTime with value set to v.
func NewOptNilDateTime(v time.Time) OptNilDateTime {
	return OptNilDateTime{
		Value: v,
		Set:   true,
	}
}

// OptNilDateTime is optional nullable time.Time.
type OptNilDateTime struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDateTime was set.
func (o OptNilDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDateTime) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilDateTime) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilInt64 returns new OptNilInt64 with value set to v.
func NewOptNilInt64(v int64) OptNilInt64 {
	return OptNilInt64{
		Value: v,
		Set:   true,
	}
}

// OptNilInt64 is optional nullable int64.
type OptNilInt64 struct {
	Value int64
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilInt64 was set.
func (o OptNilInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilInt64) SetTo(v int64) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilInt64) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilInt64) SetToNull() {
	o.Set = true
	o.Null = true
	var v int64
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilInt64) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilInt64) Get() (v int64, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilListingRef returns new OptNilListingRef with value set to v.
func NewOptNilListingRef(v ListingRef) OptNilListingRef {
	return OptNilListingRef{
		Value: v,
		Set:   true,
	}
}

// OptNilListingRef is optional nullable ListingRef.
type OptNilListingRef struct {
	Value ListingRef
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilListingRef was set.
func (o OptNilListingRef) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilListingRef) Reset() {
	var v ListingRef
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilListingRef) SetTo(v ListingRef) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilListingRef) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilListingRef) SetToNull() {
	o.Set = true
	o.Null = true
	var v ListingRef
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilListingRef) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilListingRef) Get() (v ListingRef, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilListingRef) Or(d ListingRef) ListingRef {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilRecapRef returns new OptNilRecapRef with value set to v.
func NewOptNilRecapRef(v RecapRef) OptNilRecapRef {
	return OptNilRecapRef{
		Value: v,
		Set:   true,
	}
}

// OptNilRecapRef is optional nullable RecapRef.
type OptNilRecapRef struct {
	Value RecapRef
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilRecapRef was set.
func (o OptNilRecapRef) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilRecapRef) Reset() {
	var v RecapRef
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilRecapRef) SetTo(v RecapRef) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilRecapRef) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilRecapRef) SetToNull() {
	o.Set = true
	o.Null = true
	var v RecapRef
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilRecapRef) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilRecapRef) Get() (v RecapRef, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilRecapRef) Or(d RecapRef) RecapRef {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilShareResponse returns new OptNilShareResponse with value set to v.
func NewOptNilShareResponse(v ShareResponse) OptNilShareResponse {
	return OptNilShareResponse{
		Value: v,
		Set:   true,
	}
}

// OptNilShareResponse is optional nullable ShareResponse.
type OptNilShareResponse struct {
	Value ShareResponse
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilShareResponse was set.
func (o OptNilShareResponse) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilShareResponse) Reset() {
	var v ShareResponse
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilShareResponse) SetTo(v ShareResponse) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilShareResponse) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilShareResponse) SetToNull() {
	o.Set = true
	o.Null = true
	var v ShareResponse
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilShareResponse) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilShareResponse) Get() (v ShareResponse, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilShareResponse) Or(d ShareResponse) ShareResponse {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilString) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilURI returns new OptNilURI with value set to v.
func NewOptNilURI(v url.URL) OptNilURI {
	return OptNilURI{
		Value: v,
		Set:   true,
	}
}

// OptNilURI is optional nullable url.URL.
type OptNilURI struct {
	Value url.URL
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilURI was set.
func (o OptNilURI) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilURI) Reset() {
	var v url.URL
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilURI) SetTo(v url.URL) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilURI) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilURI) SetToNull() {
	o.Set = true
	o.Null = true
	var v url.URL
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilURI) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilURI) Get() (v url.URL, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilUUID returns new OptNilUUID with value set to v.
func NewOptNilUUID(v UUID) OptNilUUID {
	return OptNilUUID{
		Value: v,
		Set:   true,
	}
}

// OptNilUUID is optional nullable UUID.
type OptNilUUID struct {
	Value UUID
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilUUID was set.
func (o OptNilUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilUUID) Reset() {
	var v UUID
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilUUID) SetTo(v UUID) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilUUID) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilUUID) SetToNull() {
	o.Set = true
	o.Null = true
	var v UUID
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilUUID) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilUUID) Get() (v UUID, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilUUID) Or(d UUID) UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptShareCardTheme returns new OptShareCardTheme with value set to v.
func NewOptShareCardTheme(v ShareCardTheme) OptShareCardTheme {
	return OptShareCardTheme{
		Value: v,
		Set:   true,
	}
}

// OptShareCardTheme is optional ShareCardTheme.
type OptShareCardTheme struct {
	Value ShareCardTheme
	Set   bool
}

// IsSet returns true if OptShareCardTheme was set.
func (o OptShareCardTheme) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptShareCardTheme) Reset() {
	var v ShareCardTheme
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptShareCardTheme) SetTo(v ShareCardTheme) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptShareCardTheme) Get() (v ShareCardTheme, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptShareCardTheme) Or(d ShareCardTheme) ShareCardTheme {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptShareRecapRequest returns new OptShareRecapRequest with value set to v.
func NewOptShareRecapRequest(v ShareRecapRequest) OptShareRecapRequest {
	return OptShareRecapRequest{
		Value: v,
		Set:   true,
	}
}

// OptShareRecapRequest is optional ShareRecapRequest.
type OptShareRecapRequest struct {
	Value ShareRecapRequest
	Set   bool
}

// IsSet returns true if OptShareRecapRequest was set.
func (o OptShareRecapRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptShareRecapRequest) Reset() {
	var v ShareRecapRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptShareRecapRequest) SetTo(v ShareRecapRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptShareRecapRequest) Get() (v ShareRecapRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptShareRecapRequest) Or(d ShareRecapRequest) ShareRecapRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptShareRecapRequestTheme returns new OptShareRecapRequestTheme with value set to v.
func NewOptShareRecapRequestTheme(v ShareRecapRequestTheme) OptShareRecapRequestTheme {
	return OptShareRecapRequestTheme{
		Value: v,
		Set:   true,
	}
}

// OptShareRecapRequestTheme is optional ShareRecapRequestTheme.
type OptShareRecapRequestTheme struct {
	Value ShareRecapRequestTheme
	Set   bool
}

// IsSet returns true if OptShareRecapRequestTheme was set.
func (o OptShareRecapRequestTheme) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptShareRecapRequestTheme) Reset() {
	var v ShareRecapRequestTheme
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptShareRecapRequestTheme) SetTo(v ShareRecapRequestTheme) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptShareRecapRequestTheme) Get() (v ShareRecapRequestTheme, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptShareRecapRequestTheme) Or(d ShareRecapRequestTheme) ShareRecapRequestTheme {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional UUID.
type OptUUID struct {
	Value UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d UUID) UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptYear returns new OptYear with value set to v.
func NewOptYear(v Year) OptYear {
	return OptYear{
		Value: v,
		Set:   true,
	}
}

// OptYear is optional Year.
type OptYear struct {
	Value Year
	Set   bool
}

// IsSet returns true if OptYear was set.
func (o OptYear) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptYear) Reset() {
	var v Year
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptYear) SetTo(v Year) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptYear) Get() (v Year, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptYear) Or(d Year) Year {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PeriodInterest
type PeriodInterest struct {
	Period      PeriodInterestPeriod `json:"period"`
	Category    CategoryRef          `json:"category"`
	Subcategory OptNilCategoryRef    `json:"subcategory"`
	// Доля активности периода, приходящаяся на эту
	// категорию, %.
	Weight OptInt32 `json:"weight"`
}

// GetPeriod returns the value of Period.
func (s *PeriodInterest) GetPeriod() PeriodInterestPeriod {
	return s.Period
}

// GetCategory returns the value of Category.
func (s *PeriodInterest) GetCategory() CategoryRef {
	return s.Category
}

// GetSubcategory returns the value of Subcategory.
func (s *PeriodInterest) GetSubcategory() OptNilCategoryRef {
	return s.Subcategory
}

// GetWeight returns the value of Weight.
func (s *PeriodInterest) GetWeight() OptInt32 {
	return s.Weight
}

// SetPeriod sets the value of Period.
func (s *PeriodInterest) SetPeriod(val PeriodInterestPeriod) {
	s.Period = val
}

// SetCategory sets the value of Category.
func (s *PeriodInterest) SetCategory(val CategoryRef) {
	s.Category = val
}

// SetSubcategory sets the value of Subcategory.
func (s *PeriodInterest) SetSubcategory(val OptNilCategoryRef) {
	s.Subcategory = val
}

// SetWeight sets the value of Weight.
func (s *PeriodInterest) SetWeight(val OptInt32) {
	s.Weight = val
}

type PeriodInterestPeriod string

const (
	PeriodInterestPeriodWinter PeriodInterestPeriod = "winter"
	PeriodInterestPeriodSpring PeriodInterestPeriod = "spring"
	PeriodInterestPeriodSummer PeriodInterestPeriod = "summer"
	PeriodInterestPeriodAutumn PeriodInterestPeriod = "autumn"
)

// AllValues returns all PeriodInterestPeriod values.
func (PeriodInterestPeriod) AllValues() []PeriodInterestPeriod {
	return []PeriodInterestPeriod{
		PeriodInterestPeriodWinter,
		PeriodInterestPeriodSpring,
		PeriodInterestPeriodSummer,
		PeriodInterestPeriodAutumn,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PeriodInterestPeriod) MarshalText() ([]byte, error) {
	switch s {
	case PeriodInterestPeriodWinter:
		return []byte(s), nil
	case PeriodInterestPeriodSpring:
		return []byte(s), nil
	case PeriodInterestPeriodSummer:
		return []byte(s), nil
	case PeriodInterestPeriodAutumn:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PeriodInterestPeriod) UnmarshalText(data []byte) error {
	switch PeriodInterestPeriod(data) {
	case PeriodInterestPeriodWinter:
		*s = PeriodInterestPeriodWinter
		return nil
	case PeriodInterestPeriodSpring:
		*s = PeriodInterestPeriodSpring
		return nil
	case PeriodInterestPeriodSummer:
		*s = PeriodInterestPeriodSummer
		return nil
	case PeriodInterestPeriodAutumn:
		*s = PeriodInterestPeriodAutumn
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Profile
type Profile struct {
	ID           UUID        `json:"id"`
	Name         string      `json:"name"`
	Surname      string      `json:"surname"`
	AvatarUrl    OptNilURI   `json:"avatarUrl"`
	RegisteredAt OptDateTime `json:"registeredAt"`
	// Короткое описание профиля для витрины выбора («что за
	// пользователь»).
	Hint OptString `json:"hint"`
	// Ссылка на уже сгенерированный recap за запрошенный год,
	// если он есть.
	Recap OptNilRecapRef `json:"recap"`
}

// GetID returns the value of ID.
func (s *Profile) GetID() UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *Profile) GetName() string {
	return s.Name
}

// GetSurname returns the value of Surname.
func (s *Profile) GetSurname() string {
	return s.Surname
}

// GetAvatarUrl returns the value of AvatarUrl.
func (s *Profile) GetAvatarUrl() OptNilURI {
	return s.AvatarUrl
}

// GetRegisteredAt returns the value of RegisteredAt.
func (s *Profile) GetRegisteredAt() OptDateTime {
	return s.RegisteredAt
}

// GetHint returns the value of Hint.
func (s *Profile) GetHint() OptString {
	return s.Hint
}

// GetRecap returns the value of Recap.
func (s *Profile) GetRecap() OptNilRecapRef {
	return s.Recap
}

// SetID sets the value of ID.
func (s *Profile) SetID(val UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Profile) SetName(val string) {
	s.Name = val
}

// SetSurname sets the value of Surname.
func (s *Profile) SetSurname(val string) {
	s.Surname = val
}

// SetAvatarUrl sets the value of AvatarUrl.
func (s *Profile) SetAvatarUrl(val OptNilURI) {
	s.AvatarUrl = val
}

// SetRegisteredAt sets the value of RegisteredAt.
func (s *Profile) SetRegisteredAt(val OptDateTime) {
	s.RegisteredAt = val
}

// SetHint sets the value of Hint.
func (s *Profile) SetHint(val OptString) {
	s.Hint = val
}

// SetRecap sets the value of Recap.
func (s *Profile) SetRecap(val OptNilRecapRef) {
	s.Recap = val
}

// Merged schema.
// Ref: #/components/schemas/PurchasesSlide
type PurchasesSlide struct {
	Type             RecapSlideType `json:"type"`
	Title            string         `json:"title"`
	Subtitle         OptString      `json:"subtitle"`
	Cta              OptNilCta      `json:"cta"`
	Purchases        int32          `json:"purchases"`
	TopCategoryTitle OptString      `json:"topCategoryTitle"`
	Badge            OptNilBadge    `json:"badge"`
}

// GetType returns the value of Type.
func (s *PurchasesSlide) GetType() RecapSlideType {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *PurchasesSlide) GetTitle() string {
	return s.Title
}

// GetSubtitle returns the value of Subtitle.
func (s *PurchasesSlide) GetSubtitle() OptString {
	return s.Subtitle
}

// GetCta returns the value of Cta.
func (s *PurchasesSlide) GetCta() OptNilCta {
	return s.Cta
}

// GetPurchases returns the value of Purchases.
func (s *PurchasesSlide) GetPurchases() int32 {
	return s.Purchases
}

// GetTopCategoryTitle returns the value of TopCategoryTitle.
func (s *PurchasesSlide) GetTopCategoryTitle() OptString {
	return s.TopCategoryTitle
}

// GetBadge returns the value of Badge.
func (s *PurchasesSlide) GetBadge() OptNilBadge {
	return s.Badge
}

// SetType sets the value of Type.
func (s *PurchasesSlide) SetType(val RecapSlideType) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *PurchasesSlide) SetTitle(val string) {
	s.Title = val
}

// SetSubtitle sets the value of Subtitle.
func (s *PurchasesSlide) SetSubtitle(val OptString) {
	s.Subtitle = val
}

// SetCta sets the value of Cta.
func (s *PurchasesSlide) SetCta(val OptNilCta) {
	s.Cta = val
}

// SetPurchases sets the value of Purchases.
func (s *PurchasesSlide) SetPurchases(val int32) {
	s.Purchases = val
}

// SetTopCategoryTitle sets the value of TopCategoryTitle.
func (s *PurchasesSlide) SetTopCategoryTitle(val OptString) {
	s.TopCategoryTitle = val
}

// SetBadge sets the value of Badge.
func (s *PurchasesSlide) SetBadge(val OptNilBadge) {
	s.Badge = val
}

// Ref: #/components/schemas/Recap
type Recap struct {
	ID        UUID        `json:"id"`
	ProfileId UUID        `json:"profileId"`
	Year      Year        `json:"year"`
	Status    RecapStatus `json:"status"`
	Archetype Archetype   `json:"archetype"`
	// Все бейджи, полученные пользователем за год.
	Badges []Badge `json:"badges"`
	// Слайды в порядке показа.
	Slides []Slide `json:"slides"`
	// Данные публичной карточки, если пользователь уже
	// делился итогами.
	Share       OptNilShareResponse `json:"share"`
	GeneratedAt time.Time           `json:"generatedAt"`
}

// GetID returns the value of ID.
func (s *Recap) GetID() UUID {
	return s.ID
}

// GetProfileId returns the value of ProfileId.
func (s *Recap) GetProfileId() UUID {
	return s.ProfileId
}

// GetYear returns the value of Year.
func (s *Recap) GetYear() Year {
	return s.Year
}

// GetStatus returns the value of Status.
func (s *Recap) GetStatus() RecapStatus {
	return s.Status
}

// GetArchetype returns the value of Archetype.
func (s *Recap) GetArchetype() Archetype {
	return s.Archetype
}

// GetBadges returns the value of Badges.
func (s *Recap) GetBadges() []Badge {
	return s.Badges
}

// GetSlides returns the value of Slides.
func (s *Recap) GetSlides() []Slide {
	return s.Slides
}

// GetShare returns the value of Share.
func (s *Recap) GetShare() OptNilShareResponse {
	return s.Share
}

// GetGeneratedAt returns the value of GeneratedAt.
func (s *Recap) GetGeneratedAt() time.Time {
	return s.GeneratedAt
}

// SetID sets the value of ID.
func (s *Recap) SetID(val UUID) {
	s.ID = val
}

// SetProfileId sets the value of ProfileId.
func (s *Recap) SetProfileId(val UUID) {
	s.ProfileId = val
}

// SetYear sets the value of Year.
func (s *Recap) SetYear(val Year) {
	s.Year = val
}

// SetStatus sets the value of Status.
func (s *Recap) SetStatus(val RecapStatus) {
	s.Status = val
}

// SetArchetype sets the value of Archetype.
func (s *Recap) SetArchetype(val Archetype) {
	s.Archetype = val
}

// SetBadges sets the value of Badges.
func (s *Recap) SetBadges(val []Badge) {
	s.Badges = val
}

// SetSlides sets the value of Slides.
func (s *Recap) SetSlides(val []Slide) {
	s.Slides = val
}

// SetShare sets the value of Share.
func (s *Recap) SetShare(val OptNilShareResponse) {
	s.Share = val
}

// SetGeneratedAt sets the value of GeneratedAt.
func (s *Recap) SetGeneratedAt(val time.Time) {
	s.GeneratedAt = val
}

func (*Recap) getRecapRes() {}

// Ref: #/components/schemas/RecapRef
type RecapRef struct {
	ID     UUID        `json:"id"`
	Year   Year        `json:"year"`
	Status RecapStatus `json:"status"`
}

// GetID returns the value of ID.
func (s *RecapRef) GetID() UUID {
	return s.ID
}

// GetYear returns the value of Year.
func (s *RecapRef) GetYear() Year {
	return s.Year
}

// GetStatus returns the value of Status.
func (s *RecapRef) GetStatus() RecapStatus {
	return s.Status
}

// SetID sets the value of ID.
func (s *RecapRef) SetID(val UUID) {
	s.ID = val
}

// SetYear sets the value of Year.
func (s *RecapRef) SetYear(val Year) {
	s.Year = val
}

// SetStatus sets the value of Status.
func (s *RecapRef) SetStatus(val RecapStatus) {
	s.Status = val
}

// Ref: #/components/schemas/SlideType
type RecapSlideType string

const (
	RecapSlideTypeIntro            RecapSlideType = "intro"
	RecapSlideTypeActiveDays       RecapSlideType = "active_days"
	RecapSlideTypeViews            RecapSlideType = "views"
	RecapSlideTypeFavorites        RecapSlideType = "favorites"
	RecapSlideTypeFavoriteCategory RecapSlideType = "favorite_category"
	RecapSlideTypePurchases        RecapSlideType = "purchases"
	RecapSlideTypeSales            RecapSlideType = "sales"
	RecapSlideTypeMessages         RecapSlideType = "messages"
	RecapSlideTypeInterests        RecapSlideType = "interests"
	RecapSlideTypeArchetype        RecapSlideType = "archetype"
	RecapSlideTypeFinal            RecapSlideType = "final"
)

// AllValues returns all RecapSlideType values.
func (RecapSlideType) AllValues() []RecapSlideType {
	return []RecapSlideType{
		RecapSlideTypeIntro,
		RecapSlideTypeActiveDays,
		RecapSlideTypeViews,
		RecapSlideTypeFavorites,
		RecapSlideTypeFavoriteCategory,
		RecapSlideTypePurchases,
		RecapSlideTypeSales,
		RecapSlideTypeMessages,
		RecapSlideTypeInterests,
		RecapSlideTypeArchetype,
		RecapSlideTypeFinal,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s RecapSlideType) MarshalText() ([]byte, error) {
	switch s {
	case RecapSlideTypeIntro:
		return []byte(s), nil
	case RecapSlideTypeActiveDays:
		return []byte(s), nil
	case RecapSlideTypeViews:
		return []byte(s), nil
	case RecapSlideTypeFavorites:
		return []byte(s), nil
	case RecapSlideTypeFavoriteCategory:
		return []byte(s), nil
	case RecapSlideTypePurchases:
		return []byte(s), nil
	case RecapSlideTypeSales:
		return []byte(s), nil
	case RecapSlideTypeMessages:
		return []byte(s), nil
	case RecapSlideTypeInterests:
		return []byte(s), nil
	case RecapSlideTypeArchetype:
		return []byte(s), nil
	case RecapSlideTypeFinal:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *RecapSlideType) UnmarshalText(data []byte) error {
	switch RecapSlideType(data) {
	case RecapSlideTypeIntro:
		*s = RecapSlideTypeIntro
		return nil
	case RecapSlideTypeActiveDays:
		*s = RecapSlideTypeActiveDays
		return nil
	case RecapSlideTypeViews:
		*s = RecapSlideTypeViews
		return nil
	case RecapSlideTypeFavorites:
		*s = RecapSlideTypeFavorites
		return nil
	case RecapSlideTypeFavoriteCategory:
		*s = RecapSlideTypeFavoriteCategory
		return nil
	case RecapSlideTypePurchases:
		*s = RecapSlideTypePurchases
		return nil
	case RecapSlideTypeSales:
		*s = RecapSlideTypeSales
		return nil
	case RecapSlideTypeMessages:
		*s = RecapSlideTypeMessages
		return nil
	case RecapSlideTypeInterests:
		*s = RecapSlideTypeInterests
		return nil
	case RecapSlideTypeArchetype:
		*s = RecapSlideTypeArchetype
		return nil
	case RecapSlideTypeFinal:
		*s = RecapSlideTypeFinal
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/RecapStatus
type RecapStatus string

const (
	RecapStatusGenerating RecapStatus = "generating"
	RecapStatusReady      RecapStatus = "ready"
	RecapStatusFailed     RecapStatus = "failed"
)

// AllValues returns all RecapStatus values.
func (RecapStatus) AllValues() []RecapStatus {
	return []RecapStatus{
		RecapStatusGenerating,
		RecapStatusReady,
		RecapStatusFailed,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s RecapStatus) MarshalText() ([]byte, error) {
	switch s {
	case RecapStatusGenerating:
		return []byte(s), nil
	case RecapStatusReady:
		return []byte(s), nil
	case RecapStatusFailed:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *RecapStatus) UnmarshalText(data []byte) error {
	switch RecapStatus(data) {
	case RecapStatusGenerating:
		*s = RecapStatusGenerating
		return nil
	case RecapStatusReady:
		*s = RecapStatusReady
		return nil
	case RecapStatusFailed:
		*s = RecapStatusFailed
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Merged schema.
// Ref: #/components/schemas/SalesSlide
type SalesSlide struct {
	Type     RecapSlideType `json:"type"`
	Title    string         `json:"title"`
	Subtitle OptString      `json:"subtitle"`
	Cta      OptNilCta      `json:"cta"`
	Sales    int32          `json:"sales"`
	// Приблизительная сумма продаж — только диапазон.
	AmountRange OptNilAmountRange `json:"amountRange"`
	// За сколько дней ушло самое быстрое объявление.
	FastestDealDays OptInt32    `json:"fastestDealDays"`
	Badge           OptNilBadge `json:"badge"`
}

// GetType returns the value of Type.
func (s *SalesSlide) GetType() RecapSlideType {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *SalesSlide) GetTitle() string {
	return s.Title
}

// GetSubtitle returns the value of Subtitle.
func (s *SalesSlide) GetSubtitle() OptString {
	return s.Subtitle
}

// GetCta returns the value of Cta.
func (s *SalesSlide) GetCta() OptNilCta {
	return s.Cta
}

// GetSales returns the value of Sales.
func (s *SalesSlide) GetSales() int32 {
	return s.Sales
}

// GetAmountRange returns the value of AmountRange.
func (s *SalesSlide) GetAmountRange() OptNilAmountRange {
	return s.AmountRange
}

// GetFastestDealDays returns the value of FastestDealDays.
func (s *SalesSlide) GetFastestDealDays() OptInt32 {
	return s.FastestDealDays
}

// GetBadge returns the value of Badge.
func (s *SalesSlide) GetBadge() OptNilBadge {
	return s.Badge
}

// SetType sets the value of Type.
func (s *SalesSlide) SetType(val RecapSlideType) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *SalesSlide) SetTitle(val string) {
	s.Title = val
}

// SetSubtitle sets the value of Subtitle.
func (s *SalesSlide) SetSubtitle(val OptString) {
	s.Subtitle = val
}

// SetCta sets the value of Cta.
func (s *SalesSlide) SetCta(val OptNilCta) {
	s.Cta = val
}

// SetSales sets the value of Sales.
func (s *SalesSlide) SetSales(val int32) {
	s.Sales = val
}

// SetAmountRange sets the value of AmountRange.
func (s *SalesSlide) SetAmountRange(val OptNilAmountRange) {
	s.AmountRange = val
}

// SetFastestDealDays sets the value of FastestDealDays.
func (s *SalesSlide) SetFastestDealDays(val OptInt32) {
	s.FastestDealDays = val
}

// SetBadge sets the value of Badge.
func (s *SalesSlide) SetBadge(val OptNilBadge) {
	s.Badge = val
}

// Публично видимая часть итогов. Содержит только
// агрегаты, которые безопасно показывать посторонним:
// без сумм, объявлений и переписок.
// Ref: #/components/schemas/ShareCard
type ShareCard struct {
	Year Year `json:"year"`
	// Имя без фамилии.
	DisplayName           OptString         `json:"displayName"`
	ArchetypeTitle        string            `json:"archetypeTitle"`
	ArchetypeDescription  OptString         `json:"archetypeDescription"`
	ActiveDays            OptInt32          `json:"activeDays"`
	FavoriteCategoryTitle OptString         `json:"favoriteCategoryTitle"`
	Badges                []Badge           `json:"badges"`
	Theme                 OptShareCardTheme `json:"theme"`
}

// GetYear returns the value of Year.
func (s *ShareCard) GetYear() Year {
	return s.Year
}

// GetDisplayName returns the value of DisplayName.
func (s *ShareCard) GetDisplayName() OptString {
	return s.DisplayName
}

// GetArchetypeTitle returns the value of ArchetypeTitle.
func (s *ShareCard) GetArchetypeTitle() string {
	return s.ArchetypeTitle
}

// GetArchetypeDescription returns the value of ArchetypeDescription.
func (s *ShareCard) GetArchetypeDescription() OptString {
	return s.ArchetypeDescription
}

// GetActiveDays returns the value of ActiveDays.
func (s *ShareCard) GetActiveDays() OptInt32 {
	return s.ActiveDays
}

// GetFavoriteCategoryTitle returns the value of FavoriteCategoryTitle.
func (s *ShareCard) GetFavoriteCategoryTitle() OptString {
	return s.FavoriteCategoryTitle
}

// GetBadges returns the value of Badges.
func (s *ShareCard) GetBadges() []Badge {
	return s.Badges
}

// GetTheme returns the value of Theme.
func (s *ShareCard) GetTheme() OptShareCardTheme {
	return s.Theme
}

// SetYear sets the value of Year.
func (s *ShareCard) SetYear(val Year) {
	s.Year = val
}

// SetDisplayName sets the value of DisplayName.
func (s *ShareCard) SetDisplayName(val OptString) {
	s.DisplayName = val
}

// SetArchetypeTitle sets the value of ArchetypeTitle.
func (s *ShareCard) SetArchetypeTitle(val string) {
	s.ArchetypeTitle = val
}

// SetArchetypeDescription sets the value of ArchetypeDescription.
func (s *ShareCard) SetArchetypeDescription(val OptString) {
	s.ArchetypeDescription = val
}

// SetActiveDays sets the value of ActiveDays.
func (s *ShareCard) SetActiveDays(val OptInt32) {
	s.ActiveDays = val
}

// SetFavoriteCategoryTitle sets the value of FavoriteCategoryTitle.
func (s *ShareCard) SetFavoriteCategoryTitle(val OptString) {
	s.FavoriteCategoryTitle = val
}

// SetBadges sets the value of Badges.
func (s *ShareCard) SetBadges(val []Badge) {
	s.Badges = val
}

// SetTheme sets the value of Theme.
func (s *ShareCard) SetTheme(val OptShareCardTheme) {
	s.Theme = val
}

type ShareCardTheme string

const (
	ShareCardThemeLight ShareCardTheme = "light"
	ShareCardThemeDark  ShareCardTheme = "dark"
)

// AllValues returns all ShareCardTheme values.
func (ShareCardTheme) AllValues() []ShareCardTheme {
	return []ShareCardTheme{
		ShareCardThemeLight,
		ShareCardThemeDark,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ShareCardTheme) MarshalText() ([]byte, error) {
	switch s {
	case ShareCardThemeLight:
		return []byte(s), nil
	case ShareCardThemeDark:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ShareCardTheme) UnmarshalText(data []byte) error {
	switch ShareCardTheme(data) {
	case ShareCardThemeLight:
		*s = ShareCardThemeLight
		return nil
	case ShareCardThemeDark:
		*s = ShareCardThemeDark
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ShareRecapBadRequest Error

func (*ShareRecapBadRequest) shareRecapRes() {}

type ShareRecapConflict Error

func (*ShareRecapConflict) shareRecapRes() {}

type ShareRecapCreated ShareResponse

func (*ShareRecapCreated) shareRecapRes() {}

type ShareRecapInternalServerError Error

func (*ShareRecapInternalServerError) shareRecapRes() {}

type ShareRecapNotFound Error

func (*ShareRecapNotFound) shareRecapRes() {}

type ShareRecapOK ShareResponse

func (*ShareRecapOK) shareRecapRes() {}

// Ref: #/components/schemas/ShareRecapRequest
type ShareRecapRequest struct {
	// Какие слайды вынести в публичную карточку. Если не
	// передано — берётся безопасный набор по умолчанию
	// (`active_days`, `favorite_category`, `archetype`). Слайды с чувствительными
	// данными (`sales`, `purchases`, `messages`, `favorites`) в карточку не
	// попадают, даже если запрошены.
	IncludeSlides []RecapSlideType          `json:"includeSlides"`
	Theme         OptShareRecapRequestTheme `json:"theme"`
}

// GetIncludeSlides returns the value of IncludeSlides.
func (s *ShareRecapRequest) GetIncludeSlides() []RecapSlideType {
	return s.IncludeSlides
}

// GetTheme returns the value of Theme.
func (s *ShareRecapRequest) GetTheme() OptShareRecapRequestTheme {
	return s.Theme
}

// SetIncludeSlides sets the value of IncludeSlides.
func (s *ShareRecapRequest) SetIncludeSlides(val []RecapSlideType) {
	s.IncludeSlides = val
}

// SetTheme sets the value of Theme.
func (s *ShareRecapRequest) SetTheme(val OptShareRecapRequestTheme) {
	s.Theme = val
}

type ShareRecapRequestTheme string

const (
	ShareRecapRequestThemeLight ShareRecapRequestTheme = "light"
	ShareRecapRequestThemeDark  ShareRecapRequestTheme = "dark"
)

// AllValues returns all ShareRecapRequestTheme values.
func (ShareRecapRequestTheme) AllValues() []ShareRecapRequestTheme {
	return []ShareRecapRequestTheme{
		ShareRecapRequestThemeLight,
		ShareRecapRequestThemeDark,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ShareRecapRequestTheme) MarshalText() ([]byte, error) {
	switch s {
	case ShareRecapRequestThemeLight:
		return []byte(s), nil
	case ShareRecapRequestThemeDark:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ShareRecapRequestTheme) UnmarshalText(data []byte) error {
	switch ShareRecapRequestTheme(data) {
	case ShareRecapRequestThemeLight:
		*s = ShareRecapRequestThemeLight
		return nil
	case ShareRecapRequestThemeDark:
		*s = ShareRecapRequestThemeDark
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ShareResponse
type ShareResponse struct {
	// Публичный токен карточки (не UUID, чтобы id recap не утекал в
	// ссылку).
	Token string  `json:"token"`
	URL   url.URL `json:"url"`
	// Пререндеренная картинка карточки для соцсетей.
	ImageUrl  OptNilURI `json:"imageUrl"`
	Card      ShareCard `json:"card"`
	CreatedAt time.Time `json:"createdAt"`
	// `null` — ссылка бессрочная.
	ExpiresAt OptNilDateTime `json:"expiresAt"`
}

// GetToken returns the value of Token.
func (s *ShareResponse) GetToken() string {
	return s.Token
}

// GetURL returns the value of URL.
func (s *ShareResponse) GetURL() url.URL {
	return s.URL
}

// GetImageUrl returns the value of ImageUrl.
func (s *ShareResponse) GetImageUrl() OptNilURI {
	return s.ImageUrl
}

// GetCard returns the value of Card.
func (s *ShareResponse) GetCard() ShareCard {
	return s.Card
}

// GetCreatedAt returns the value of CreatedAt.
func (s *ShareResponse) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *ShareResponse) GetExpiresAt() OptNilDateTime {
	return s.ExpiresAt
}

// SetToken sets the value of Token.
func (s *ShareResponse) SetToken(val string) {
	s.Token = val
}

// SetURL sets the value of URL.
func (s *ShareResponse) SetURL(val url.URL) {
	s.URL = val
}

// SetImageUrl sets the value of ImageUrl.
func (s *ShareResponse) SetImageUrl(val OptNilURI) {
	s.ImageUrl = val
}

// SetCard sets the value of Card.
func (s *ShareResponse) SetCard(val ShareCard) {
	s.Card = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *ShareResponse) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *ShareResponse) SetExpiresAt(val OptNilDateTime) {
	s.ExpiresAt = val
}

// Ref: #/components/schemas/Slide
// Slide represents sum type.
type Slide struct {
	// Type selects the active sum variant, switch on this field.
	Type            SlideType
	IntroSlide      IntroSlide
	ActiveDaysSlide ActiveDaysSlide
	ViewsSlide      ViewsSlide
	FavoritesSlide  FavoritesSlide
	CategorySlide   CategorySlide
	PurchasesSlide  PurchasesSlide
	SalesSlide      SalesSlide
	MessagesSlide   MessagesSlide
	InterestsSlide  InterestsSlide
	ArchetypeSlide  ArchetypeSlide
	FinalSlide      FinalSlide
}

// SlideType is oneOf type of Slide.
type SlideType string

// Possible values for SlideType.
const (
	IntroSlideSlide      SlideType = "intro"
	ActiveDaysSlideSlide SlideType = "active_days"
	ViewsSlideSlide      SlideType = "views"
	FavoritesSlideSlide  SlideType = "favorites"
	CategorySlideSlide   SlideType = "favorite_category"
	PurchasesSlideSlide  SlideType = "purchases"
	SalesSlideSlide      SlideType = "sales"
	MessagesSlideSlide   SlideType = "messages"
	InterestsSlideSlide  SlideType = "interests"
	ArchetypeSlideSlide  SlideType = "archetype"
	FinalSlideSlide      SlideType = "final"
)

// IsIntroSlide reports whether Slide is IntroSlide.
func (s Slide) IsIntroSlide() bool { return s.Type == IntroSlideSlide }

// IsActiveDaysSlide reports whether Slide is ActiveDaysSlide.
func (s Slide) IsActiveDaysSlide() bool { return s.Type == ActiveDaysSlideSlide }

// IsViewsSlide reports whether Slide is ViewsSlide.
func (s Slide) IsViewsSlide() bool { return s.Type == ViewsSlideSlide }

// IsFavoritesSlide reports whether Slide is FavoritesSlide.
func (s Slide) IsFavoritesSlide() bool { return s.Type == FavoritesSlideSlide }

// IsCategorySlide reports whether Slide is CategorySlide.
func (s Slide) IsCategorySlide() bool { return s.Type == CategorySlideSlide }

// IsPurchasesSlide reports whether Slide is PurchasesSlide.
func (s Slide) IsPurchasesSlide() bool { return s.Type == PurchasesSlideSlide }

// IsSalesSlide reports whether Slide is SalesSlide.
func (s Slide) IsSalesSlide() bool { return s.Type == SalesSlideSlide }

// IsMessagesSlide reports whether Slide is MessagesSlide.
func (s Slide) IsMessagesSlide() bool { return s.Type == MessagesSlideSlide }

// IsInterestsSlide reports whether Slide is InterestsSlide.
func (s Slide) IsInterestsSlide() bool { return s.Type == InterestsSlideSlide }

// IsArchetypeSlide reports whether Slide is ArchetypeSlide.
func (s Slide) IsArchetypeSlide() bool { return s.Type == ArchetypeSlideSlide }

// IsFinalSlide reports whether Slide is FinalSlide.
func (s Slide) IsFinalSlide() bool { return s.Type == FinalSlideSlide }

// SetIntroSlide sets Slide to IntroSlide.
func (s *Slide) SetIntroSlide(v IntroSlide) {
	s.Type = IntroSlideSlide
	s.IntroSlide = v
}

// GetIntroSlide returns IntroSlide and true boolean if Slide is IntroSlide.
func (s Slide) GetIntroSlide() (v IntroSlide, ok bool) {
	if !s.IsIntroSlide() {
		return v, false
	}
	return s.IntroSlide, true
}

// NewIntroSlideSlide returns new Slide from IntroSlide.
func NewIntroSlideSlide(v IntroSlide) Slide {
	var s Slide
	s.SetIntroSlide(v)
	return s
}

// SetActiveDaysSlide sets Slide to ActiveDaysSlide.
func (s *Slide) SetActiveDaysSlide(v ActiveDaysSlide) {
	s.Type = ActiveDaysSlideSlide
	s.ActiveDaysSlide = v
}

// GetActiveDaysSlide returns ActiveDaysSlide and true boolean if Slide is ActiveDaysSlide.
func (s Slide) GetActiveDaysSlide() (v ActiveDaysSlide, ok bool) {
	if !s.IsActiveDaysSlide() {
		return v, false
	}
	return s.ActiveDaysSlide, true
}

// NewActiveDaysSlideSlide returns new Slide from ActiveDaysSlide.
func NewActiveDaysSlideSlide(v ActiveDaysSlide) Slide {
	var s Slide
	s.SetActiveDaysSlide(v)
	return s
}

// SetViewsSlide sets Slide to ViewsSlide.
func (s *Slide) SetViewsSlide(v ViewsSlide) {
	s.Type = ViewsSlideSlide
	s.ViewsSlide = v
}

// GetViewsSlide returns ViewsSlide and true boolean if Slide is ViewsSlide.
func (s Slide) GetViewsSlide() (v ViewsSlide, ok bool) {
	if !s.IsViewsSlide() {
		return v, false
	}
	return s.ViewsSlide, true
}

// NewViewsSlideSlide returns new Slide from ViewsSlide.
func NewViewsSlideSlide(v ViewsSlide) Slide {
	var s Slide
	s.SetViewsSlide(v)
	return s
}

// SetFavoritesSlide sets Slide to FavoritesSlide.
func (s *Slide) SetFavoritesSlide(v FavoritesSlide) {
	s.Type = FavoritesSlideSlide
	s.FavoritesSlide = v
}

// GetFavoritesSlide returns FavoritesSlide and true boolean if Slide is FavoritesSlide.
func (s Slide) GetFavoritesSlide() (v FavoritesSlide, ok bool) {
	if !s.IsFavoritesSlide() {
		return v, false
	}
	return s.FavoritesSlide, true
}

// NewFavoritesSlideSlide returns new Slide from FavoritesSlide.
func NewFavoritesSlideSlide(v FavoritesSlide) Slide {
	var s Slide
	s.SetFavoritesSlide(v)
	return s
}

// SetCategorySlide sets Slide to CategorySlide.
func (s *Slide) SetCategorySlide(v CategorySlide) {
	s.Type = CategorySlideSlide
	s.CategorySlide = v
}

// GetCategorySlide returns CategorySlide and true boolean if Slide is CategorySlide.
func (s Slide) GetCategorySlide() (v CategorySlide, ok bool) {
	if !s.IsCategorySlide() {
		return v, false
	}
	return s.CategorySlide, true
}

// NewCategorySlideSlide returns new Slide from CategorySlide.
func NewCategorySlideSlide(v CategorySlide) Slide {
	var s Slide
	s.SetCategorySlide(v)
	return s
}

// SetPurchasesSlide sets Slide to PurchasesSlide.
func (s *Slide) SetPurchasesSlide(v PurchasesSlide) {
	s.Type = PurchasesSlideSlide
	s.PurchasesSlide = v
}

// GetPurchasesSlide returns PurchasesSlide and true boolean if Slide is PurchasesSlide.
func (s Slide) GetPurchasesSlide() (v PurchasesSlide, ok bool) {
	if !s.IsPurchasesSlide() {
		return v, false
	}
	return s.PurchasesSlide, true
}

// NewPurchasesSlideSlide returns new Slide from PurchasesSlide.
func NewPurchasesSlideSlide(v PurchasesSlide) Slide {
	var s Slide
	s.SetPurchasesSlide(v)
	return s
}

// SetSalesSlide sets Slide to SalesSlide.
func (s *Slide) SetSalesSlide(v SalesSlide) {
	s.Type = SalesSlideSlide
	s.SalesSlide = v
}

// GetSalesSlide returns SalesSlide and true boolean if Slide is SalesSlide.
func (s Slide) GetSalesSlide() (v SalesSlide, ok bool) {
	if !s.IsSalesSlide() {
		return v, false
	}
	return s.SalesSlide, true
}

// NewSalesSlideSlide returns new Slide from SalesSlide.
func NewSalesSlideSlide(v SalesSlide) Slide {
	var s Slide
	s.SetSalesSlide(v)
	return s
}

// SetMessagesSlide sets Slide to MessagesSlide.
func (s *Slide) SetMessagesSlide(v MessagesSlide) {
	s.Type = MessagesSlideSlide
	s.MessagesSlide = v
}

// GetMessagesSlide returns MessagesSlide and true boolean if Slide is MessagesSlide.
func (s Slide) GetMessagesSlide() (v MessagesSlide, ok bool) {
	if !s.IsMessagesSlide() {
		return v, false
	}
	return s.MessagesSlide, true
}

// NewMessagesSlideSlide returns new Slide from MessagesSlide.
func NewMessagesSlideSlide(v MessagesSlide) Slide {
	var s Slide
	s.SetMessagesSlide(v)
	return s
}

// SetInterestsSlide sets Slide to InterestsSlide.
func (s *Slide) SetInterestsSlide(v InterestsSlide) {
	s.Type = InterestsSlideSlide
	s.InterestsSlide = v
}

// GetInterestsSlide returns InterestsSlide and true boolean if Slide is InterestsSlide.
func (s Slide) GetInterestsSlide() (v InterestsSlide, ok bool) {
	if !s.IsInterestsSlide() {
		return v, false
	}
	return s.InterestsSlide, true
}

// NewInterestsSlideSlide returns new Slide from InterestsSlide.
func NewInterestsSlideSlide(v InterestsSlide) Slide {
	var s Slide
	s.SetInterestsSlide(v)
	return s
}

// SetArchetypeSlide sets Slide to ArchetypeSlide.
func (s *Slide) SetArchetypeSlide(v ArchetypeSlide) {
	s.Type = ArchetypeSlideSlide
	s.ArchetypeSlide = v
}

// GetArchetypeSlide returns ArchetypeSlide and true boolean if Slide is ArchetypeSlide.
func (s Slide) GetArchetypeSlide() (v ArchetypeSlide, ok bool) {
	if !s.IsArchetypeSlide() {
		return v, false
	}
	return s.ArchetypeSlide, true
}

// NewArchetypeSlideSlide returns new Slide from ArchetypeSlide.
func NewArchetypeSlideSlide(v ArchetypeSlide) Slide {
	var s Slide
	s.SetArchetypeSlide(v)
	return s
}

// SetFinalSlide sets Slide to FinalSlide.
func (s *Slide) SetFinalSlide(v FinalSlide) {
	s.Type = FinalSlideSlide
	s.FinalSlide = v
}

// GetFinalSlide returns FinalSlide and true boolean if Slide is FinalSlide.
func (s Slide) GetFinalSlide() (v FinalSlide, ok bool) {
	if !s.IsFinalSlide() {
		return v, false
	}
	return s.FinalSlide, true
}

// NewFinalSlideSlide returns new Slide from FinalSlide.
func NewFinalSlideSlide(v FinalSlide) Slide {
	var s Slide
	s.SetFinalSlide(v)
	return s
}

// TooManyRequestsHeaders wraps Error with response headers.
type TooManyRequestsHeaders struct {
	RetryAfter OptInt32
	Response   Error
}

// GetRetryAfter returns the value of RetryAfter.
func (s *TooManyRequestsHeaders) GetRetryAfter() OptInt32 {
	return s.RetryAfter
}

// GetResponse returns the value of Response.
func (s *TooManyRequestsHeaders) GetResponse() Error {
	return s.Response
}

// SetRetryAfter sets the value of RetryAfter.
func (s *TooManyRequestsHeaders) SetRetryAfter(val OptInt32) {
	s.RetryAfter = val
}

// SetResponse sets the value of Response.
func (s *TooManyRequestsHeaders) SetResponse(val Error) {
	s.Response = val
}

func (*TooManyRequestsHeaders) createRecapRes() {}
func (*TooManyRequestsHeaders) shareRecapRes()  {}

type UUID uuid.UUID

// Merged schema.
// Ref: #/components/schemas/ViewsSlide
type ViewsSlide struct {
	Type             RecapSlideType `json:"type"`
	Title            string         `json:"title"`
	Subtitle         OptString      `json:"subtitle"`
	Cta              OptNilCta      `json:"cta"`
	Views            int64          `json:"views"`
	UniqueListings   OptInt64       `json:"uniqueListings"`
	TopCategoryTitle OptString      `json:"topCategoryTitle"`
}

// GetType returns the value of Type.
func (s *ViewsSlide) GetType() RecapSlideType {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *ViewsSlide) GetTitle() string {
	return s.Title
}

// GetSubtitle returns the value of Subtitle.
func (s *ViewsSlide) GetSubtitle() OptString {
	return s.Subtitle
}

// GetCta returns the value of Cta.
func (s *ViewsSlide) GetCta() OptNilCta {
	return s.Cta
}

// GetViews returns the value of Views.
func (s *ViewsSlide) GetViews() int64 {
	return s.Views
}

// GetUniqueListings returns the value of UniqueListings.
func (s *ViewsSlide) GetUniqueListings() OptInt64 {
	return s.UniqueListings
}

// GetTopCategoryTitle returns the value of TopCategoryTitle.
func (s *ViewsSlide) GetTopCategoryTitle() OptString {
	return s.TopCategoryTitle
}

// SetType sets the value of Type.
func (s *ViewsSlide) SetType(val RecapSlideType) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *ViewsSlide) SetTitle(val string) {
	s.Title = val
}

// SetSubtitle sets the value of Subtitle.
func (s *ViewsSlide) SetSubtitle(val OptString) {
	s.Subtitle = val
}

// SetCta sets the value of Cta.
func (s *ViewsSlide) SetCta(val OptNilCta) {
	s.Cta = val
}

// SetViews sets the value of Views.
func (s *ViewsSlide) SetViews(val int64) {
	s.Views = val
}

// SetUniqueListings sets the value of UniqueListings.
func (s *ViewsSlide) SetUniqueListings(val OptInt64) {
	s.UniqueListings = val
}

// SetTopCategoryTitle sets the value of TopCategoryTitle.
func (s *ViewsSlide) SetTopCategoryTitle(val OptString) {
	s.TopCategoryTitle = val
}

type Year int32
