// Code generated by ogen, DO NOT EDIT.
package api

type CreateRecapRes interface {
	createRecapRes()
}

type GetRecapRes interface {
	getRecapRes()
}

type ListProfilesRes interface {
	listProfilesRes()
}

type ShareRecapRes interface {
	shareRecapRes()
}
